spring.application.name=event-service
weather.service.url=${WEATHER_SERVICE_URL:https://climatecast-6lun.onrender.com}
server.port=${PORT:8080}
# Disable MongoDB auto-configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
